[package]
name = "gridcore-core"
version = "0.1.0"
edition = "2024"

[dependencies]
chumsky = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true }
petgraph = { workspace = true }
regex = { workspace = true }
chrono = { workspace = true }

[features]
default = []
wasm = [
  "dep:wasm-bindgen",
  "dep:js-sys",
  "dep:web-sys",
  "dep:serde-wasm-bindgen",
  "dep:serde_json",
]

[dependencies.wasm-bindgen]
workspace = true
optional = true

[dependencies.js-sys]
workspace = true
optional = true

[dependencies.web-sys]
workspace = true
optional = true

[dependencies.serde-wasm-bindgen]
workspace = true
optional = true

[dependencies.serde_json]
workspace = true
optional = true

[dev-dependencies]
criterion = "0.5"

[[bench]]
name = "transformer_bench"
harness = false

[[bench]]
name = "structural_ops_bench"
harness = false

[[bench]]
name = "undo_redo_benchmark"
harness = false

