# Cargo configuration for WASM optimization

[build]
target = "wasm32-unknown-unknown"

# Additional optimization flags
[target.wasm32-unknown-unknown]
rustflags = [
  "-C", "link-arg=--no-entry",
  "-C", "link-arg=--export-dynamic",
  "-C", "opt-level=z",
]

# For nightly builds (optional - uncomment if using nightly)
# [unstable]
# build-std = ["std", "panic_abort", "core", "alloc"]
# build-std-features = ["panic_immediate_abort"]