[workspace]
members = ["gridcore-core", "gridcore-wasm"]
resolver = "2"

[workspace.dependencies]
chumsky = { version = "0.10", default-features = false, features = ["pratt"] }
thiserror = "2.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde-wasm-bindgen = "0.6"
wasm-bindgen = "0.2"
petgraph = "0.8"
js-sys = "0.3"
web-sys = "0.3"

