[package]
name = "gridcore-ui"
version = "0.1.0"
edition = "2024"

[dependencies]
gridcore-core = { path = "../gridcore-core" }
gridcore-controller = { path = "../gridcore-controller" }
leptos = { version = "0.8", features = ["csr"] }
leptos_dom = "0.8"
leptos_reactive = "0.6"
web-sys = { version = "0.3", features = [
  "CanvasRenderingContext2d",
  "HtmlCanvasElement",
  "Window",
  "Document",
  "Element",
  "HtmlElement",
  "MouseEvent",
  "KeyboardEvent",
  "WheelEvent",
  "DomRect",
  "CssStyleDeclaration",
] }
wasm-bindgen = "0.2"
console_error_panic_hook = "0.1"
