# Trunk build configuration
# https://trunkrs.dev/configuration/

[build]
target = "index.html"
dist = "dist"
# Use the optimized wasm-release profile for release builds
release = true
# Specify cargo profile for release builds
cargo_profile = "wasm-release"
# Minify HTML/CSS/JS on release builds
minify = "on_release"

[watch]
watch = ["src", "Cargo.toml", "index.html", "style"]

[serve]
addresses = ["127.0.0.1"]
port = 8080
open = false

# Remove proxy configuration as we don't need it for now
# [[proxy]]
# rewrite = "/api"
# backend = "http://localhost:3000/"

# Post-build hook for WASM optimization
[[hooks]]
stage = "post_build"
command = "bash"
command_arguments = ["scripts/optimize-wasm.sh"]