# Trunk build configuration
# https://trunkrs.dev/configuration/

[build]
target = "index.html"
dist = "dist"

[watch]
watch = ["src", "Cargo.toml", "index.html", "style"]

[serve]
addresses = ["127.0.0.1"]
port = 8080
open = false

# Remove proxy configuration as we don't need it for now
# [[proxy]]
# rewrite = "/api"
# backend = "http://localhost:3000/"